export const vuelosRealistas = [
  { id: 'v1', aerolinea: 'LATAM Airlines', origen: 'Quito (UIO)', destino: 'Madrid (MAD)', duracion: '10h 50m', precio: 850, tipo: 'vuelo', proveedor: 'Expedia', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=LATAM&background=E8114B&color=fff&size=128' },
  { id: 'v2', aerolinea: 'Iberia', origen: 'Guayaquil (GYE)', destino: 'Madrid (MAD)', duracion: '11h 15m', precio: 920, tipo: 'vuelo', proveedor: 'Booking.com', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=Iberia&background=DF0024&color=fff&size=128' },
  { id: 'v3', aerolinea: 'Air Europa', origen: 'Quito (UIO)', destino: 'Madrid (MAD)', duracion: '10h 40m', precio: 810, tipo: 'vuelo', proveedor: 'Kayak', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=Air+Europa&background=0033A0&color=fff&size=128' },
  { id: 'v4', aerolinea: 'Avianca', origen: 'Quito (UIO)', destino: 'Baltra (GPS)', duracion: '2h 15m', precio: 150, tipo: 'vuelo', proveedor: 'Avianca.com', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=Avianca&background=E1251B&color=fff&size=128' },
  { id: 'v5', aerolinea: 'LATAM Airlines', origen: 'Guayaquil (GYE)', destino: 'San Cristóbal (SCY)', duracion: '1h 50m', precio: 120, tipo: 'vuelo', proveedor: 'Expedia', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=LATAM&background=E8114B&color=fff&size=128' },
  { id: 'v6', aerolinea: 'KLM', origen: 'Quito (UIO)', destino: 'Amsterdam (AMS)', duracion: '11h 30m', precio: 980, tipo: 'vuelo', proveedor: 'Kayak', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=KLM&background=00A1DE&color=fff&size=128' },
  { id: 'v7', aerolinea: 'American Airlines', origen: 'Guayaquil (GYE)', destino: 'Miami (MIA)', duracion: '4h 15m', precio: 350, tipo: 'vuelo', proveedor: 'Expedia', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=American&background=1782D2&color=fff&size=128' },
  { id: 'v8', aerolinea: 'Copa Airlines', origen: 'Quito (UIO)', destino: 'Panamá (PTY)', duracion: '2h 00m', precio: 220, tipo: 'vuelo', proveedor: 'Booking.com', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=Copa&background=0032A0&color=fff&size=128' },
  { id: 'v9', aerolinea: 'Delta', origen: 'Quito (UIO)', destino: 'Atlanta (ATL)', duracion: '5h 20m', precio: 450, tipo: 'vuelo', proveedor: 'Kayak', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=Delta&background=E51420&color=fff&size=128' },
  { id: 'v10', aerolinea: 'United Airlines', origen: 'Quito (UIO)', destino: 'Houston (IAH)', duracion: '5h 10m', precio: 480, tipo: 'vuelo', proveedor: 'Expedia', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=United&background=005DAA&color=fff&size=128' },
  { id: 'v11', aerolinea: 'Avianca', origen: 'Guayaquil (GYE)', destino: 'Bogotá (BOG)', duracion: '1h 40m', precio: 180, tipo: 'vuelo', proveedor: 'Avianca.com', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=Avianca&background=E1251B&color=fff&size=128' },
  { id: 'v12', aerolinea: 'LATAM Airlines', origen: 'Quito (UIO)', destino: 'Lima (LIM)', duracion: '2h 20m', precio: 240, tipo: 'vuelo', proveedor: 'Booking.com', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=LATAM&background=E8114B&color=fff&size=128' },
  { id: 'v13', aerolinea: 'Iberia', origen: 'Quito (UIO)', destino: 'Barcelona (BCN)', duracion: '13h 00m', precio: 1050, tipo: 'vuelo', proveedor: 'Expedia', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=Iberia&background=DF0024&color=fff&size=128' },
  { id: 'v14', aerolinea: 'Air France', origen: 'Quito (UIO)', destino: 'Paris (CDG)', duracion: '14h 20m', precio: 1150, tipo: 'vuelo', proveedor: 'Kayak', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=Air+France&background=002157&color=fff&size=128' },
  { id: 'v15', aerolinea: 'Copa Airlines', origen: 'Guayaquil (GYE)', destino: 'Cancún (CUN)', duracion: '6h 30m', precio: 380, tipo: 'vuelo', proveedor: 'Expedia', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=Copa&background=0032A0&color=fff&size=128' },
  { id: 'v16', aerolinea: 'Aeroméxico', origen: 'Quito (UIO)', destino: 'CDMX (MEX)', duracion: '5h 45m', precio: 410, tipo: 'vuelo', proveedor: 'Booking.com', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=Aeromexico&background=001659&color=fff&size=128' },
  { id: 'v17', aerolinea: 'American Airlines', origen: 'Quito (UIO)', destino: 'Nueva York (JFK)', duracion: '8h 10m', precio: 550, tipo: 'vuelo', proveedor: 'Kayak', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=American&background=1782D2&color=fff&size=128' },
  { id: 'v18', aerolinea: 'LATAM Airlines', origen: 'Guayaquil (GYE)', destino: 'Buenos Aires (EZE)', duracion: '6h 00m', precio: 490, tipo: 'vuelo', proveedor: 'Expedia', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=LATAM&background=E8114B&color=fff&size=128' },
  { id: 'v19', aerolinea: 'JetBlue', origen: 'Guayaquil (GYE)', destino: 'Fort Lauderdale (FLL)', duracion: '4h 25m', precio: 290, tipo: 'vuelo', proveedor: 'Booking.com', escalas: 'Directo', logo: 'https://ui-avatars.com/api/?name=JetBlue&background=0033A0&color=fff&size=128' },
  { id: 'v20', aerolinea: 'Avianca', origen: 'Quito (UIO)', destino: 'Cartagena (CTG)', duracion: '4h 50m', precio: 270, tipo: 'vuelo', proveedor: 'Kayak', escalas: '1 Escala', logo: 'https://ui-avatars.com/api/?name=Avianca&background=E1251B&color=fff&size=128' },
];

export const hotelesRealistas = [
  // Madrid
  { id: 'h1', nombre: 'Hyatt Regency Hesperia Madrid', ciudad: 'Madrid', estrellas: 5, precioNoche: 196, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/luxury,hotel?lock=1', lat: 40.4379, lng: -3.6914, proveedor: 'Booking.com', rating: 8.5, resenas: 991, comodidades: 'Cancelación gratis' },
  { id: 'h2', nombre: 'Barceló Torre de Madrid', ciudad: 'Madrid', estrellas: 5, precioNoche: 210, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/luxury,hotel?lock=2', lat: 40.4239, lng: -3.7122, proveedor: 'Expedia', rating: 9.1, resenas: 1205, comodidades: 'Piscina, Spa' },
  { id: 'h3', nombre: 'Porcel Ganivet', ciudad: 'Madrid', estrellas: 3, precioNoche: 136, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,room?lock=3', lat: 40.4079, lng: -3.7118, proveedor: 'Hotels.com', rating: 8.8, resenas: 6596, comodidades: 'Desayuno incluido' },
  { id: 'h4', nombre: 'NH Collection Madrid', ciudad: 'Madrid', estrellas: 4, precioNoche: 165, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,lobby?lock=4', lat: 40.4192, lng: -3.7001, proveedor: 'Kayak', rating: 8.9, resenas: 3100, comodidades: 'Wifi, Gimnasio' },
  { id: 'h5', nombre: 'Hotel Riu Plaza España', ciudad: 'Madrid', estrellas: 4, precioNoche: 180, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,bedroom?lock=5', lat: 40.4234, lng: -3.7115, proveedor: 'Booking.com', rating: 9.2, resenas: 8500, comodidades: 'Terraza, Piscina' },
  // Quito
  { id: 'h6', nombre: 'Swissôtel Quito', ciudad: 'Quito', estrellas: 5, precioNoche: 145, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/resort,pool?lock=6', lat: -0.2037, lng: -78.4827, proveedor: 'Expedia', rating: 9.0, resenas: 850, comodidades: 'Piscina, Spa, Gym' },
  { id: 'h7', nombre: 'JW Marriott Hotel Quito', ciudad: 'Quito', estrellas: 5, precioNoche: 160, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,lobby?lock=7', lat: -0.1982, lng: -78.4871, proveedor: 'Marriott', rating: 9.2, resenas: 1100, comodidades: 'Cancelación gratis' },
  { id: 'h8', nombre: 'Hotel Dann Carlton', ciudad: 'Quito', estrellas: 4, precioNoche: 90, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,bedroom?lock=8', lat: -0.1837, lng: -78.4815, proveedor: 'Booking.com', rating: 8.7, resenas: 640, comodidades: 'Desayuno incluido' },
  { id: 'h9', nombre: 'Illa Experience Hotel', ciudad: 'Quito', estrellas: 5, precioNoche: 220, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/boutique,hotel?lock=9', lat: -0.2223, lng: -78.5135, proveedor: 'Kayak', rating: 9.8, resenas: 350, comodidades: 'Boutique, Spa' },
  { id: 'h10', nombre: 'Casa Gangotena', ciudad: 'Quito', estrellas: 5, precioNoche: 350, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/luxury,hotel,historic?lock=10', lat: -0.2205, lng: -78.5152, proveedor: 'Expedia', rating: 9.7, resenas: 700, comodidades: 'Desayuno premium, Terraza' },
  // Guayaquil
  { id: 'h11', nombre: 'Hotel Oro Verde', ciudad: 'Guayaquil', estrellas: 5, precioNoche: 120, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/luxury,hotel?lock=11', lat: -2.1887, lng: -79.8894, proveedor: 'Booking.com', rating: 9.3, resenas: 2100, comodidades: 'Restaurante 5 estrellas' },
  { id: 'h12', nombre: 'Wyndham Guayaquil', ciudad: 'Guayaquil', estrellas: 5, precioNoche: 135, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/resort,hotel?lock=12', lat: -2.1793, lng: -79.8732, proveedor: 'Expedia', rating: 9.0, resenas: 1540, comodidades: 'Vista al río, Piscina' },
  { id: 'h13', nombre: 'Sheraton Guayaquil Hotel', ciudad: 'Guayaquil', estrellas: 5, precioNoche: 110, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,lobby?lock=13', lat: -2.1554, lng: -79.8945, proveedor: 'Marriott', rating: 8.8, resenas: 1300, comodidades: 'Spa, Casino' },
  { id: 'h14', nombre: 'Hilton Colón Guayaquil', ciudad: 'Guayaquil', estrellas: 5, precioNoche: 125, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,pool?lock=14', lat: -2.1645, lng: -79.8998, proveedor: 'Booking.com', rating: 9.1, resenas: 2500, comodidades: 'Piscina, Gimnasio' },
  { id: 'h15', nombre: 'Holiday Inn Guayaquil', ciudad: 'Guayaquil', estrellas: 4, precioNoche: 85, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,room?lock=15', lat: -2.1485, lng: -79.8833, proveedor: 'Expedia', rating: 8.6, resenas: 980, comodidades: 'Cerca del aeropuerto' },
  // Galápagos
  { id: 'h16', nombre: 'Finch Bay Galapagos Hotel', ciudad: 'Galápagos', estrellas: 5, precioNoche: 450, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/resort,beach?lock=16', lat: -0.7512, lng: -90.3155, proveedor: 'Expedia', rating: 9.6, resenas: 420, comodidades: 'Frente al mar, Piscina' },
  { id: 'h17', nombre: 'Golden Bay Hotel & Spa', ciudad: 'Galápagos', estrellas: 4, precioNoche: 280, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/spa,hotel?lock=17', lat: -0.9025, lng: -89.6101, proveedor: 'Booking.com', rating: 9.3, resenas: 310, comodidades: 'Spa, Desayuno incluido' },
  { id: 'h18', nombre: 'Ikala Galapagos Hotel', ciudad: 'Galápagos', estrellas: 4, precioNoche: 210, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/boutique,hotel?lock=18', lat: -0.7456, lng: -90.3121, proveedor: 'Kayak', rating: 9.0, resenas: 580, comodidades: 'Terraza, Bar' },
  { id: 'h19', nombre: 'Hotel Sol y Mar', ciudad: 'Galápagos', estrellas: 4, precioNoche: 250, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,ocean?lock=19', lat: -0.7445, lng: -90.3142, proveedor: 'Hotels.com', rating: 9.2, resenas: 850, comodidades: 'Vista al mar' },
  { id: 'h20', nombre: 'Isla Dorada', ciudad: 'Galápagos', estrellas: 3, precioNoche: 110, tipo: 'hotel', imagen: 'https://loremflickr.com/600/400/hotel,room?lock=20', lat: -0.7420, lng: -90.3100, proveedor: 'Booking.com', rating: 8.4, resenas: 240, comodidades: 'Wifi, A/C' },
];

export const autosRealistas = [
  { id: 'a1', empresa: 'Avis Rent a Car', modelo: 'Chevrolet Tracker (SUV)', ciudad: 'Quito', precioDia: 45, tipo: 'auto', proveedor: 'Avis', rating: 8.5, lat: -0.1807, lng: -78.4678, imagen: 'https://loremflickr.com/600/400/suv,car?lock=1' },
  { id: 'a2', empresa: 'Hertz', modelo: 'Kia Rio (Sedan)', ciudad: 'Madrid', precioDia: 35, tipo: 'auto', proveedor: 'Hertz', rating: 9.0, lat: 40.4719, lng: -3.5626, imagen: 'https://loremflickr.com/600/400/sedan,car?lock=2' },
  { id: 'a3', empresa: 'Localiza', modelo: 'Toyota Fortuner (4x4)', ciudad: 'Quito', precioDia: 65, tipo: 'auto', proveedor: 'Localiza', rating: 8.2, lat: -0.1700, lng: -78.4750, imagen: 'https://loremflickr.com/600/400/4x4,jeep?lock=3' },
  { id: 'a4', empresa: 'Budget', modelo: 'Hyundai Tucson (SUV)', ciudad: 'Guayaquil', precioDia: 50, tipo: 'auto', proveedor: 'Budget', rating: 8.8, lat: -2.1550, lng: -79.8900, imagen: 'https://loremflickr.com/600/400/suv,car?lock=4' },
  { id: 'a5', empresa: 'Enterprise', modelo: 'Ford Escape (SUV)', ciudad: 'Quito', precioDia: 55, tipo: 'auto', proveedor: 'Enterprise', rating: 9.1, lat: -0.1650, lng: -78.4800, imagen: 'https://loremflickr.com/600/400/suv,car?lock=5' },
  { id: 'a6', empresa: 'Alamo', modelo: 'Nissan Versa (Sedan)', ciudad: 'Madrid', precioDia: 30, tipo: 'auto', proveedor: 'Alamo', rating: 8.7, lat: 40.4650, lng: -3.5700, imagen: 'https://loremflickr.com/600/400/sedan,car?lock=6' },
  { id: 'a7', empresa: 'Sixt', modelo: 'BMW X3 (Premium SUV)', ciudad: 'Madrid', precioDia: 85, tipo: 'auto', proveedor: 'Sixt', rating: 9.5, lat: 40.4700, lng: -3.5600, imagen: 'https://loremflickr.com/600/400/bmw,car?lock=7' },
  { id: 'a8', empresa: 'Hertz', modelo: 'Chevrolet Spark (Compact)', ciudad: 'Guayaquil', precioDia: 25, tipo: 'auto', proveedor: 'Hertz', rating: 8.1, lat: -2.1600, lng: -79.8950, imagen: 'https://loremflickr.com/600/400/compact,car?lock=8' },
  { id: 'a9', empresa: 'Avis Rent a Car', modelo: 'Toyota Hilux (Pickup)', ciudad: 'Quito', precioDia: 75, tipo: 'auto', proveedor: 'Avis', rating: 8.9, lat: -0.1850, lng: -78.4700, imagen: 'https://loremflickr.com/600/400/pickup,truck?lock=9' },
  { id: 'a10', empresa: 'Localiza', modelo: 'Renault Logan (Sedan)', ciudad: 'Guayaquil', precioDia: 28, tipo: 'auto', proveedor: 'Localiza', rating: 8.3, lat: -2.1700, lng: -79.8800, imagen: 'https://loremflickr.com/600/400/sedan,car?lock=10' },
  { id: 'a11', empresa: 'Budget', modelo: 'Volkswagen Jetta (Sedan)', ciudad: 'Madrid', precioDia: 40, tipo: 'auto', proveedor: 'Budget', rating: 8.6, lat: 40.4500, lng: -3.6000, imagen: 'https://loremflickr.com/600/400/volkswagen,sedan?lock=11' },
  { id: 'a12', empresa: 'Enterprise', modelo: 'Kia Sportage (SUV)', ciudad: 'Guayaquil', precioDia: 48, tipo: 'auto', proveedor: 'Enterprise', rating: 9.0, lat: -2.1500, lng: -79.8850, imagen: 'https://loremflickr.com/600/400/suv,car?lock=12' },
  { id: 'a13', empresa: 'Alamo', modelo: 'Hyundai Accent (Sedan)', ciudad: 'Quito', precioDia: 32, tipo: 'auto', proveedor: 'Alamo', rating: 8.5, lat: -0.1900, lng: -78.4850, imagen: 'https://loremflickr.com/600/400/sedan,car?lock=13' },
  { id: 'a14', empresa: 'Sixt', modelo: 'Mercedes-Benz C-Class', ciudad: 'Madrid', precioDia: 95, tipo: 'auto', proveedor: 'Sixt', rating: 9.7, lat: 40.4800, lng: -3.5500, imagen: 'https://loremflickr.com/600/400/mercedes,car?lock=14' },
  { id: 'a15', empresa: 'Avis Rent a Car', modelo: 'Toyota Yaris (Compact)', ciudad: 'Guayaquil', precioDia: 27, tipo: 'auto', proveedor: 'Avis', rating: 8.4, lat: -2.1800, lng: -79.8700, imagen: 'https://loremflickr.com/600/400/compact,car?lock=15' },
  { id: 'a16', empresa: 'Hertz', modelo: 'Nissan Qashqai (SUV)', ciudad: 'Quito', precioDia: 52, tipo: 'auto', proveedor: 'Hertz', rating: 8.8, lat: -0.1750, lng: -78.4750, imagen: 'https://loremflickr.com/600/400/suv,car?lock=16' },
  { id: 'a17', empresa: 'Localiza', modelo: 'Chevrolet D-Max (Pickup)', ciudad: 'Quito', precioDia: 70, tipo: 'auto', proveedor: 'Localiza', rating: 8.6, lat: -0.1600, lng: -78.4900, imagen: 'https://loremflickr.com/600/400/pickup,truck?lock=17' },
  { id: 'a18', empresa: 'Budget', modelo: 'Seat Leon (Compact)', ciudad: 'Madrid', precioDia: 33, tipo: 'auto', proveedor: 'Budget', rating: 8.9, lat: 40.4600, lng: -3.5800, imagen: 'https://loremflickr.com/600/400/compact,car?lock=18' },
  { id: 'a19', empresa: 'Enterprise', modelo: 'Toyota Corolla (Sedan)', ciudad: 'Quito', precioDia: 38, tipo: 'auto', proveedor: 'Enterprise', rating: 9.2, lat: -0.1950, lng: -78.4800, imagen: 'https://loremflickr.com/600/400/sedan,car?lock=19' },
  { id: 'a20', empresa: 'Alamo', modelo: 'Honda CR-V (SUV)', ciudad: 'Guayaquil', precioDia: 55, tipo: 'auto', proveedor: 'Alamo', rating: 9.1, lat: -2.1650, lng: -79.8900, imagen: 'https://loremflickr.com/600/400/suv,car?lock=20' },
];

export const restaurantesRealistas = [
  { id: 'r1', nombre: 'Zazu', ciudad: 'Quito', tipoComida: 'Contemporánea / Ecuatoriana', precioPromedio: '$$$', tipo: 'restaurante', lat: -0.1925, lng: -78.4836, rating: 9.5, resenas: 1250, imagen: 'https://loremflickr.com/600/400/restaurant,food?lock=1', proveedor: 'TripAdvisor' },
  { id: 'r2', nombre: 'DiverXO', ciudad: 'Madrid', tipoComida: 'Alta Cocina', precioPromedio: '$$$$', tipo: 'restaurante', lat: 40.4589, lng: -3.6900, rating: 9.8, resenas: 3400, imagen: 'https://loremflickr.com/600/400/gourmet,food?lock=2', proveedor: 'Michelin' },
  { id: 'r3', nombre: 'La Pizarra', ciudad: 'Guayaquil', tipoComida: 'Tapas Ecuatorianas', precioPromedio: '$$', tipo: 'restaurante', lat: -2.1750, lng: -79.8800, rating: 8.9, resenas: 890, imagen: 'https://loremflickr.com/600/400/tapas,food?lock=3', proveedor: 'TripAdvisor' },
  { id: 'r4', nombre: 'Sobrino de Botín', ciudad: 'Madrid', tipoComida: 'Española', precioPromedio: '$$$', tipo: 'restaurante', lat: 40.4140, lng: -3.7075, rating: 9.2, resenas: 8500, imagen: 'https://loremflickr.com/600/400/spanish,food?lock=4', proveedor: 'TripAdvisor' },
  { id: 'r5', nombre: 'Somos', ciudad: 'Quito', tipoComida: 'Fusión Ecuatoriana', precioPromedio: '$$$', tipo: 'restaurante', lat: -0.1900, lng: -78.4800, rating: 9.4, resenas: 600, imagen: 'https://loremflickr.com/600/400/cuisine,food?lock=5', proveedor: 'TripAdvisor' },
  { id: 'r6', nombre: 'Nuema', ciudad: 'Quito', tipoComida: 'Alta Cocina Ecuatoriana', precioPromedio: '$$$$', tipo: 'restaurante', lat: -0.2000, lng: -78.4850, rating: 9.7, resenas: 800, imagen: 'https://loremflickr.com/600/400/gourmet,chef?lock=6', proveedor: 'Michelin' },
  { id: 'r7', nombre: 'Pujol', ciudad: 'Madrid', tipoComida: 'Mexicana', precioPromedio: '$$$', tipo: 'restaurante', lat: 40.4200, lng: -3.7000, rating: 9.1, resenas: 2100, imagen: 'https://loremflickr.com/600/400/mexican,food?lock=7', proveedor: 'TripAdvisor' },
  { id: 'r8', nombre: 'Casa Julián', ciudad: 'Guayaquil', tipoComida: 'Ecuatoriana Tradicional', precioPromedio: '$$$', tipo: 'restaurante', lat: -2.1400, lng: -79.8700, rating: 9.6, resenas: 1100, imagen: 'https://loremflickr.com/600/400/seafood,plate?lock=8', proveedor: 'TripAdvisor' },
  { id: 'r9', nombre: 'Urko', ciudad: 'Quito', tipoComida: 'Degustación', precioPromedio: '$$$$', tipo: 'restaurante', lat: -0.1950, lng: -78.4750, rating: 9.5, resenas: 450, imagen: 'https://loremflickr.com/600/400/fine,dining?lock=9', proveedor: 'TripAdvisor' },
  { id: 'r10', nombre: 'El Paraguas', ciudad: 'Madrid', tipoComida: 'Asturiana', precioPromedio: '$$$', tipo: 'restaurante', lat: 40.4250, lng: -3.6850, rating: 9.3, resenas: 3200, imagen: 'https://loremflickr.com/600/400/meat,food?lock=10', proveedor: 'Michelin' },
  { id: 'r11', nombre: 'Micaela', ciudad: 'Guayaquil', tipoComida: 'Parrilla', precioPromedio: '$$', tipo: 'restaurante', lat: -2.1600, lng: -79.8900, rating: 8.8, resenas: 750, imagen: 'https://loremflickr.com/600/400/steak,food?lock=11', proveedor: 'TripAdvisor' },
  { id: 'r12', nombre: 'Ten Con Ten', ciudad: 'Madrid', tipoComida: 'Mediterránea', precioPromedio: '$$$', tipo: 'restaurante', lat: 40.4300, lng: -3.6900, rating: 9.0, resenas: 4100, imagen: 'https://loremflickr.com/600/400/mediterranean,food?lock=12', proveedor: 'TripAdvisor' },
  { id: 'r13', nombre: 'Carmine', ciudad: 'Quito', tipoComida: 'Italiana', precioPromedio: '$$', tipo: 'restaurante', lat: -0.1850, lng: -78.4700, rating: 8.7, resenas: 920, imagen: 'https://loremflickr.com/600/400/pasta,food?lock=13', proveedor: 'TripAdvisor' },
  { id: 'r14', nombre: 'La Gloria', ciudad: 'Quito', tipoComida: 'Fusión', precioPromedio: '$$$', tipo: 'restaurante', lat: -0.1800, lng: -78.4650, rating: 9.1, resenas: 1050, imagen: 'https://loremflickr.com/600/400/fusion,food?lock=14', proveedor: 'TripAdvisor' },
  { id: 'r15', nombre: 'Pescador', ciudad: 'Guayaquil', tipoComida: 'Mariscos', precioPromedio: '$$', tipo: 'restaurante', lat: -2.1800, lng: -79.8800, rating: 9.0, resenas: 1300, imagen: 'https://loremflickr.com/600/400/seafood,fish?lock=15', proveedor: 'TripAdvisor' },
  { id: 'r16', nombre: 'StreetXO', ciudad: 'Madrid', tipoComida: 'Fusión Asiática', precioPromedio: '$$', tipo: 'restaurante', lat: 40.4280, lng: -3.7050, rating: 9.4, resenas: 5500, imagen: 'https://loremflickr.com/600/400/asian,food?lock=16', proveedor: 'Michelin' },
  { id: 'r17', nombre: 'Cosa Nostra', ciudad: 'Quito', tipoComida: 'Pizza', precioPromedio: '$', tipo: 'restaurante', lat: -0.2100, lng: -78.4900, rating: 8.5, resenas: 1800, imagen: 'https://loremflickr.com/600/400/pizza,food?lock=17', proveedor: 'TripAdvisor' },
  { id: 'r18', nombre: 'Lo Nuestro', ciudad: 'Guayaquil', tipoComida: 'Criolla', precioPromedio: '$$', tipo: 'restaurante', lat: -2.1500, lng: -79.9000, rating: 9.2, resenas: 2200, imagen: 'https://loremflickr.com/600/400/traditional,food?lock=18', proveedor: 'TripAdvisor' },
  { id: 'r19', nombre: 'Punto MX', ciudad: 'Madrid', tipoComida: 'Mexicana', precioPromedio: '$$$', tipo: 'restaurante', lat: 40.4350, lng: -3.6700, rating: 9.5, resenas: 1900, imagen: 'https://loremflickr.com/600/400/tacos,food?lock=19', proveedor: 'Michelin' },
  { id: 'r20', nombre: 'Zielo', ciudad: 'Quito', tipoComida: 'Internacional', precioPromedio: '$$', tipo: 'restaurante', lat: -0.1700, lng: -78.4600, rating: 8.9, resenas: 850, imagen: 'https://loremflickr.com/600/400/salad,food?lock=20', proveedor: 'TripAdvisor' },
];

export const actividadesPorCiudad = {
  Quito: [
    { id: 'act-q1', titulo: 'Teleférico y Volcán Pichincha', duracion: 'Medio Día', precio: 25, tipo: 'actividad', lat: -0.1853, lng: -78.5204, rating: 9.1, resenas: 2500, imagen: 'https://loremflickr.com/600/400/mountain,view?lock=1', proveedor: 'GetYourGuide' },
    { id: 'act-q2', titulo: 'Tour Centro Histórico', duracion: '3 Horas', precio: 15, tipo: 'actividad', lat: -0.2202, lng: -78.5123, rating: 9.5, resenas: 4200, imagen: 'https://loremflickr.com/600/400/historic,city?lock=2', proveedor: 'Viator' },
    { id: 'act-q3', titulo: 'Visita Mitad del Mundo', duracion: 'Medio Día', precio: 20, tipo: 'actividad', lat: -0.0022, lng: -78.4558, rating: 9.2, resenas: 3800, imagen: 'https://loremflickr.com/600/400/monument,park?lock=3', proveedor: 'GetYourGuide' },
    { id: 'act-q4', titulo: 'Trekking en el Cotopaxi', duracion: 'Día Completo', precio: 65, tipo: 'actividad', lat: -0.6800, lng: -78.4300, rating: 9.7, resenas: 1500, imagen: 'https://loremflickr.com/600/400/volcano,hiking?lock=4', proveedor: 'Viator' },
    { id: 'act-q5', titulo: 'Tour Nocturno de Leyendas', duracion: '2 Horas', precio: 12, tipo: 'actividad', lat: -0.2180, lng: -78.5100, rating: 8.9, resenas: 950, imagen: 'https://loremflickr.com/600/400/city,night?lock=5', proveedor: 'GetYourGuide' }
  ],
  Madrid: [
    { id: 'act-m1', titulo: 'Museo del Prado', duracion: 'Medio Día', precio: 20, tipo: 'actividad', lat: 40.4138, lng: -3.6921, rating: 9.7, resenas: 12000, imagen: 'https://loremflickr.com/600/400/museum,art?lock=6', proveedor: 'GetYourGuide' },
    { id: 'act-m2', titulo: 'Tour por el Estadio Santiago Bernabéu', duracion: '2 Horas', precio: 25, tipo: 'actividad', lat: 40.4531, lng: -3.6883, rating: 9.3, resenas: 8500, imagen: 'https://loremflickr.com/600/400/stadium,football?lock=7', proveedor: 'Viator' },
    { id: 'act-m3', titulo: 'Palacio Real de Madrid', duracion: '3 Horas', precio: 18, tipo: 'actividad', lat: 40.4179, lng: -3.7143, rating: 9.5, resenas: 9200, imagen: 'https://loremflickr.com/600/400/palace,architecture?lock=8', proveedor: 'GetYourGuide' },
    { id: 'act-m4', titulo: 'Espectáculo Flamenco', duracion: '1.5 Horas', precio: 35, tipo: 'actividad', lat: 40.4150, lng: -3.7050, rating: 9.6, resenas: 4500, imagen: 'https://loremflickr.com/600/400/flamenco,dance?lock=9', proveedor: 'Viator' },
    { id: 'act-m5', titulo: 'Tour de Tapas', duracion: '3 Horas', precio: 45, tipo: 'actividad', lat: 40.4130, lng: -3.7080, rating: 9.4, resenas: 3100, imagen: 'https://loremflickr.com/600/400/tapas,spain?lock=10', proveedor: 'GetYourGuide' }
  ],
  Guayaquil: [
    { id: 'act-g1', titulo: 'Paseo Malecón 2000 y Las Peñas', duracion: '3 Horas', precio: 10, tipo: 'actividad', lat: -2.1852, lng: -79.8776, rating: 8.8, resenas: 1500, imagen: 'https://loremflickr.com/600/400/river,city?lock=11', proveedor: 'GetYourGuide' },
    { id: 'act-g2', titulo: 'Parque Histórico de Guayaquil', duracion: 'Medio Día', precio: 15, tipo: 'actividad', lat: -2.1400, lng: -79.8650, rating: 9.0, resenas: 2100, imagen: 'https://loremflickr.com/600/400/park,nature?lock=12', proveedor: 'Viator' },
    { id: 'act-g3', titulo: 'Tour Isla Santay', duracion: '3 Horas', precio: 12, tipo: 'actividad', lat: -2.2000, lng: -79.8600, rating: 8.7, resenas: 850, imagen: 'https://loremflickr.com/600/400/bridge,nature?lock=13', proveedor: 'GetYourGuide' },
    { id: 'act-g4', titulo: 'Crucero Morgan por el Río Guayas', duracion: '2 Horas', precio: 20, tipo: 'actividad', lat: -2.1800, lng: -79.8750, rating: 8.9, resenas: 1200, imagen: 'https://loremflickr.com/600/400/boat,river?lock=14', proveedor: 'Viator' },
    { id: 'act-g5', titulo: 'Jardín Botánico', duracion: '2 Horas', precio: 8, tipo: 'actividad', lat: -2.1500, lng: -79.9100, rating: 8.5, resenas: 450, imagen: 'https://loremflickr.com/600/400/botanical,garden?lock=15', proveedor: 'GetYourGuide' }
  ],
  Galápagos: [
    { id: 'act-ga1', titulo: 'Tour Diario a Isla Bartolomé', duracion: '1 Día', precio: 180, tipo: 'actividad', lat: -0.2831, lng: -90.5516, rating: 9.8, resenas: 950, imagen: 'https://loremflickr.com/600/400/island,beach?lock=16', proveedor: 'Viator' },
    { id: 'act-ga2', titulo: 'Snorkel en León Dormido', duracion: 'Medio Día', precio: 120, tipo: 'actividad', lat: -0.7600, lng: -89.5100, rating: 9.7, resenas: 1100, imagen: 'https://loremflickr.com/600/400/snorkeling,ocean?lock=17', proveedor: 'GetYourGuide' },
    { id: 'act-ga3', titulo: 'Visita a Tortuga Bay', duracion: 'Medio Día', precio: 0, tipo: 'actividad', lat: -0.7620, lng: -90.3300, rating: 9.9, resenas: 3500, imagen: 'https://loremflickr.com/600/400/beach,sand?lock=18', proveedor: 'Viator' },
    { id: 'act-ga4', titulo: 'Tour Estación Charles Darwin', duracion: '2 Horas', precio: 10, tipo: 'actividad', lat: -0.7400, lng: -90.3000, rating: 9.0, resenas: 2800, imagen: 'https://loremflickr.com/600/400/turtle,animal?lock=19', proveedor: 'GetYourGuide' },
    { id: 'act-ga5', titulo: 'Buceo en Isla Seymour Norte', duracion: 'Día Completo', precio: 200, tipo: 'actividad', lat: -0.3900, lng: -90.2800, rating: 9.6, resenas: 600, imagen: 'https://loremflickr.com/600/400/scuba,diving?lock=20', proveedor: 'Viator' }
  ]
};
