export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTRO: "/registro",
  MIS_VIAJES: "/mis-viajes",
  DESTINATIONS: "/destinos",
  BLOG: "/blog",
  CONTACT: "/contactos",
  RESERVAS: "/reservas",
  CONFIGURACION: "/configuracion",
  EXPERIENCIAS_CATEGORIA: "/experiencias/:categoria",
  PLANIFICADOR: "/planificador",
  DASHBOARD: "/dashboard",
  VUELOS: "/vuelos",
  HOTELES: "/hoteles",
  AUTOS: "/autos",
  RESTAURANTES: "/restaurantes",
  ACTIVIDADES: "/actividades",
};
